### ISSUE TITLE
Add more k8s labels to instances managed by container-jfr-operator

### ISSUE THREAD

**Issue by jiekang** [rh-jmc-team/container-jfr-operator#60]
For example, the Jaeger RH operator adds the following labels to it's Jaeger instances:

```
app
=
jaeger
app.kubernetes.io/component
=
all-in-one
app.kubernetes.io/instance
=
jaeger-all-in-one-inmemory
app.kubernetes.io/managed-by
=
jaeger-operator
app.kubernetes.io/name
=
jaeger-all-in-one-inmemory
app.kubernetes.io/part-of
=
jaeger
pod-template-hash
=
856b547bf
```

**Comment by andrewazores** [comment]
We do have the `app.kubernetes.io/name` label which is applied to the ContainerJFR Deployment. Are these labels also on the Jaeger Deployment? Are there any other resources or component associated with the Jaeger operator?

**Comment by jiekang** [comment]
Yes these labels are applied to the Jaeger Deployment which is created from an instance of ResourceKind Jager. Hopefully I understood the question.

Regarding other resources/components, I'll get back to you in a day on that.

**Comment by jiekang** [comment]
The Jaeger ResourceKind is also associated with:

ReplicaSet
Pod
Service
ConfigMap
Secret

The above, excluding Secret have the labels I listed above with the correct fields.

**Comment by jiekang** [comment]
In comparison, the ContainerJFR ResourceKind instance has resources:
Pod
Service (4)

We will need to make sure it is connected to all the resources.

**Comment by andrewazores** [comment]
Where is this "ResourceKind instance" from? I'm not sure how I can tell which things are linked together in the way you're talking about.

**Comment by jiekang** [comment]
@andrewazores 
Hmm I think my terminology is incorrect or maybe outdated sorry. These are maybe called instances of the CRDs? E.g. a yaml with Kind: ContainerJFR or Kind: Jaeger.

In the console if you view an installed operator, there should be a tab for "All Instances" and one for each kind of instance.

**Comment by andrewazores** [comment]
Ah, okay I see what you mean. I'm not sure how the console is populating that list that you're seeing. It might be coming from the OperatorHub ClusterServiceVersion, but this is what we currently have in the list of the operator's owned resources:

```yaml
  customresourcedefinitions:
    owned:
      - name: containerjfrs.rhjmc.redhat.com
        displayName: ContainerJFR
        kind: ContainerJFR
        version: v1alpha1
        description: Container JFR
        resources:
          - version: v1
            kind: Deployment
          - version: v1
            kind: Service
          - version: v1
            kind: ReplicaSet
          - version: v1
            kind: Pod
          - version: v1
            kind: Secret
          - version: v1
            kind: ConfigMap
        specDescriptors: []
        statusDescriptors: []
```

So the "make sure it is connected to all resources" is a piece that I don't really know how to address, since it looks like it should already be set up for what you're looking for, but I don't know how the UI is determining it.

It may simply be that our CSV is claiming that we own those resources, but don't actually use any in practice - the ContainerJFR CRD represents the Operator's view of what a container-jfr looks like, which basically just means "one container-jfr container and its exporter and command-channel services, a persistent volume, and optionally grafana/jfr-datasource containers and associated services". All of those containers get wrapped up into a Pod, which is managed by a Deployment/ReplicaSet and which all services point back to, but the Deployment/ReplicaSet belong to the Operator - the ContainerJFR lives inside of those resources, rather than owning them.
